// Generated by gencpp from file light_robot/AddTwoInts.msg
// DO NOT EDIT!


#ifndef LIGHT_ROBOT_MESSAGE_ADDTWOINTS_H
#define LIGHT_ROBOT_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <light_robot/AddTwoIntsRequest.h>
#include <light_robot/AddTwoIntsResponse.h>


namespace light_robot
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace light_robot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::light_robot::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::light_robot::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::light_robot::AddTwoInts > {
  static const char* value()
  {
    return "light_robot/AddTwoInts";
  }

  static const char* value(const ::light_robot::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::light_robot::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::light_robot::AddTwoInts >
template<>
struct MD5Sum< ::light_robot::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::light_robot::AddTwoInts >::value();
  }
  static const char* value(const ::light_robot::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::light_robot::AddTwoIntsRequest> should match
// service_traits::DataType< ::light_robot::AddTwoInts >
template<>
struct DataType< ::light_robot::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::light_robot::AddTwoInts >::value();
  }
  static const char* value(const ::light_robot::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::light_robot::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::light_robot::AddTwoInts >
template<>
struct MD5Sum< ::light_robot::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::light_robot::AddTwoInts >::value();
  }
  static const char* value(const ::light_robot::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::light_robot::AddTwoIntsResponse> should match
// service_traits::DataType< ::light_robot::AddTwoInts >
template<>
struct DataType< ::light_robot::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::light_robot::AddTwoInts >::value();
  }
  static const char* value(const ::light_robot::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LIGHT_ROBOT_MESSAGE_ADDTWOINTS_H
