// Generated by gencpp from file light_robot/wordResponse.msg
// DO NOT EDIT!


#ifndef LIGHT_ROBOT_MESSAGE_WORDRESPONSE_H
#define LIGHT_ROBOT_MESSAGE_WORDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace light_robot
{
template <class ContainerAllocator>
struct wordResponse_
{
  typedef wordResponse_<ContainerAllocator> Type;

  wordResponse_()
    : number(0)  {
    }
  wordResponse_(const ContainerAllocator& _alloc)
    : number(0)  {
  (void)_alloc;
    }



   typedef int64_t _number_type;
  _number_type number;





  typedef boost::shared_ptr< ::light_robot::wordResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::light_robot::wordResponse_<ContainerAllocator> const> ConstPtr;

}; // struct wordResponse_

typedef ::light_robot::wordResponse_<std::allocator<void> > wordResponse;

typedef boost::shared_ptr< ::light_robot::wordResponse > wordResponsePtr;
typedef boost::shared_ptr< ::light_robot::wordResponse const> wordResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::light_robot::wordResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::light_robot::wordResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::light_robot::wordResponse_<ContainerAllocator1> & lhs, const ::light_robot::wordResponse_<ContainerAllocator2> & rhs)
{
  return lhs.number == rhs.number;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::light_robot::wordResponse_<ContainerAllocator1> & lhs, const ::light_robot::wordResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace light_robot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::light_robot::wordResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::light_robot::wordResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::light_robot::wordResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::light_robot::wordResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::light_robot::wordResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::light_robot::wordResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::light_robot::wordResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2a1b249ff0900a6eb941a743f359017a";
  }

  static const char* value(const ::light_robot::wordResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2a1b249ff0900a6eULL;
  static const uint64_t static_value2 = 0xb941a743f359017aULL;
};

template<class ContainerAllocator>
struct DataType< ::light_robot::wordResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "light_robot/wordResponse";
  }

  static const char* value(const ::light_robot::wordResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::light_robot::wordResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 number \n"
"\n"
;
  }

  static const char* value(const ::light_robot::wordResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::light_robot::wordResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.number);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct wordResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::light_robot::wordResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::light_robot::wordResponse_<ContainerAllocator>& v)
  {
    s << indent << "number: ";
    Printer<int64_t>::stream(s, indent + "  ", v.number);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIGHT_ROBOT_MESSAGE_WORDRESPONSE_H
