// Generated by gencpp from file light_robot/wordRequest.msg
// DO NOT EDIT!


#ifndef LIGHT_ROBOT_MESSAGE_WORDREQUEST_H
#define LIGHT_ROBOT_MESSAGE_WORDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace light_robot
{
template <class ContainerAllocator>
struct wordRequest_
{
  typedef wordRequest_<ContainerAllocator> Type;

  wordRequest_()
    : word()  {
    }
  wordRequest_(const ContainerAllocator& _alloc)
    : word(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _word_type;
  _word_type word;





  typedef boost::shared_ptr< ::light_robot::wordRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::light_robot::wordRequest_<ContainerAllocator> const> ConstPtr;

}; // struct wordRequest_

typedef ::light_robot::wordRequest_<std::allocator<void> > wordRequest;

typedef boost::shared_ptr< ::light_robot::wordRequest > wordRequestPtr;
typedef boost::shared_ptr< ::light_robot::wordRequest const> wordRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::light_robot::wordRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::light_robot::wordRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::light_robot::wordRequest_<ContainerAllocator1> & lhs, const ::light_robot::wordRequest_<ContainerAllocator2> & rhs)
{
  return lhs.word == rhs.word;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::light_robot::wordRequest_<ContainerAllocator1> & lhs, const ::light_robot::wordRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace light_robot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::light_robot::wordRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::light_robot::wordRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::light_robot::wordRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::light_robot::wordRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::light_robot::wordRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::light_robot::wordRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::light_robot::wordRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cf5cbdd7f0c6b9eaa898f882ab6eade6";
  }

  static const char* value(const ::light_robot::wordRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcf5cbdd7f0c6b9eaULL;
  static const uint64_t static_value2 = 0xa898f882ab6eade6ULL;
};

template<class ContainerAllocator>
struct DataType< ::light_robot::wordRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "light_robot/wordRequest";
  }

  static const char* value(const ::light_robot::wordRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::light_robot::wordRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string word \n"
"\n"
;
  }

  static const char* value(const ::light_robot::wordRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::light_robot::wordRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.word);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct wordRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::light_robot::wordRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::light_robot::wordRequest_<ContainerAllocator>& v)
  {
    s << indent << "word: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.word);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIGHT_ROBOT_MESSAGE_WORDREQUEST_H
